
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.embassy-executor]
audit-as-crates-io = false

[policy.embassy-executor-macros]
audit-as-crates-io = false

[policy.embassy-futures]
audit-as-crates-io = false

[policy.embassy-hal-internal]
audit-as-crates-io = false

[policy.embassy-imxrt]
audit-as-crates-io = false

[policy.embassy-sync]
audit-as-crates-io = false

[policy.embassy-time]
audit-as-crates-io = false

[policy.embassy-time-driver]
audit-as-crates-io = false

[policy.embassy-time-queue-utils]
audit-as-crates-io = false

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.arraydeque]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.az]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.bare-metal]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield-macros]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.40"
criteria = "safe-to-deploy"

[[exemptions.cobs]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cortex-m]]
version = "0.7.7"
criteria = "safe-to-deploy"

[[exemptions.cortex-m-rt]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.cortex-m-rt-macros]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.crc]]
version = "3.2.1"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.dd-manifest-tree]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "0.3.100"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.device-driver]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.device-driver-generation]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.device-driver-macros]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-async]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-nb]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-io-async]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-storage]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-storage-async]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.fixed]]
version = "1.29.0"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.mimxrt600-fcb]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.mimxrt685s-pac]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.postcard]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.semver-parser]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.100"
criteria = "safe-to-deploy"

[[exemptions.tap]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.vcell]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.volatile-register]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"
